# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: moeykens.net 
email: vincent (at) moeykens.net
email_mailaddress: vincent@moeykens.net
description: > # this means to ignore newlines until "baseurl:"
  Landing page for moeykens.net.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moeykens.net" # the base hostname & protocol for your site
github_username:  vmoeykens

# Build settings
markdown: kramdown
